"""initial-migration

Revision ID: 636d6fcd7be4
Revises: 
Create Date: 2026-07-27 13:33:21.817992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '636d6fcd7be4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('character_class', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lvl', sa.Integer(), nullable=False),
    sa.Column('stat_str', sa.Integer(), nullable=False),
    sa.Column('stat_dex', sa.Integer(), nullable=False),
    sa.Column('stat_con', sa.Integer(), nullable=False),
    sa.Column('stat_int', sa.Integer(), nullable=False),
    sa.Column('stat_wis', sa.Integer(), nullable=False),
    sa.Column('stat_cha', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spell',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lvl', sa.Integer(), nullable=False),
    sa.Column('school', sa.Enum('BANNMAGIE', 'BESCHWOERUNG', 'ERKENNTNISMAGIE', 'HERVORRUFUNG', 'ILLUSION', 'NEKROMATIE', 'VERWANDLUNG', 'VERZAUBERUNG', name='spellschool'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characterspelllink',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'spell_id')
    )
    op.create_table('item',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'MYTHICAL', 'LEGENDARY', name='itemrarity'), nullable=False),
    sa.Column('worth', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('damage_dice', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('characterspelllink')
    op.drop_table('spell')
    op.drop_table('character')
    # ### end Alembic commands ###
