"""initiate all tables

Revision ID: 907b320e14f8
Revises:
Create Date: 2026-07-29 14:27:56.488618

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "907b320e14f8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "character_class", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("lvl", sa.Integer(), nullable=False),
        sa.Column("stat_str", sa.Integer(), nullable=False),
        sa.Column("stat_dex", sa.Integer(), nullable=False),
        sa.Column("stat_con", sa.Integer(), nullable=False),
        sa.Column("stat_int", sa.Integer(), nullable=False),
        sa.Column("stat_wis", sa.Integer(), nullable=False),
        sa.Column("stat_cha", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "spell",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lvl", sa.Integer(), nullable=False),
        sa.Column(
            "school",
            sa.Enum(
                "BANNMAGIE",
                "BESCHWOERUNG",
                "ERKENNTNISMAGIE",
                "HERVORRUFUNG",
                "ILLUSION",
                "NEKROMATIE",
                "VERWANDLUNG",
                "VERZAUBERUNG",
                name="spellschool",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("PLAYER", "DUNGEON_MASTER", "ADMIN", name="userrole"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    op.create_table(
        "characterspelllink",
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("spell_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["character.id"],
        ),
        sa.ForeignKeyConstraint(
            ["spell_id"],
            ["spell.id"],
        ),
        sa.PrimaryKeyConstraint("character_id", "spell_id"),
    )
    op.create_table(
        "item",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "rarity",
            sa.Enum("COMMON", "RARE", "MYTHICAL", "LEGENDARY", name="itemrarity"),
            nullable=False,
        ),
        sa.Column("worth", sa.Integer(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("damage_dice", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"], ["character.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("item")
    op.drop_table("characterspelllink")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    op.drop_table("spell")
    op.drop_table("character")
    # ### end Alembic commands ###
